<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RefCore\RefCore.fsproj" />
    <ProjectReference Include="..\RefUtil\RefUtil.fsproj" />
    <ProjectReference Include="..\RefMiddle\RefMiddle.fsproj" />
  </ItemGroup>

</Project>
